name: Test

on:
  workflow_dispatch:
    branches:
      - '**'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.13
      - name: Run tests
        run: ./gradlew --console=plain test
      - name: Archive test reports
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-reports
          path: build/reports/
